
#' MakeBoxPlot
#'
#' Make one or more box plots on the basis of sample statistics as generated by \code{\link{ds.GetSampleStatistics}}. Makes use of ggplot2.
#'
#' @param SampleStatistics Data frame | Sample statistics as generated by \code{\link{ds.GetSampleStatistics}}
#' @param AxisLimits_y Vector | Containing two integer values | Default: Auto y axis limits
#' @param AxisTitle_x
#' @param AxisTitle_y
#' @param TickLabelWidth_x
#' @param Decimals Number of decimals of y axis number format
#' @param ggTheme Pass custom theme
#' @param ThemeArguments Pass custom theme arguments
#' @param FillPalette
#' @param ...
#'
#' @return a ggplot2 object
#' @export
#'
#' @examples
#' @author Bastian Reiter
MakeBoxPlot <- function(SampleStatistics,
                        AxisLimits_y = c(NA_integer_, NA_integer_),
                        AxisTitle_x = "",
                        AxisTitle_y = "",
                        TickLabelWidth_x = 10,
                        Decimals = 0,
                        ggTheme = function(...) dsCCPhosClient::ggTheme_CCP(...),
                        ThemeArguments = list(),
                        FillPalette = NULL,
                        ...)
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
{
    require(dplyr)
    require(ggplot2)
    require(scales)


    #--- Process plot data -----------------------------------------------------

    df_PlotData <- data.frame(x = SampleStatistics$Server,
                              ymin = SampleStatistics$q5,
                              lower = SampleStatistics$Q1,
                              middle = SampleStatistics$Median,
                              upper = SampleStatistics$Q3,
                              ymax = SampleStatistics$q95,
                              mean = SampleStatistics$Mean)


    #--- Plot ------------------------------------------------------------------

    # Create boxplot using ggplot2
    Plot <- ggplot(data = df_PlotData,
                   aes(x = x,
                       ymin = ymin,
                       lower = lower,
                       middle = middle,
                       upper = upper,
                       ymax = ymax,
                       fill = x)) +
                do.call(ggTheme, c(list(...),
                                   list(SizeFactorTickLabels_x = 1.3),      # Increase x axis tick label text size by default
                                   ThemeArguments)) +      # Pass additional optional arguments
                geom_boxplot(stat = "identity",      # Important for drawing boxplot with own computations
                             width = 0.4,
                             alpha = 0.7,
                             outlier.shape = NA,
                             show.legend = FALSE) +
                geom_point(aes(y = mean),
                           color = CCPhosColors$Accent,
                           size = 3,
                           shape = 19,
                           show.legend = FALSE) +
                labs(x = AxisTitle_x,
                     y = AxisTitle_y) +
                #--- Option: If no axis title, delete space for label --------------
                {
                  if (AxisTitle_x == "") { theme(axis.title.x = element_blank()) }
                } + {
                  if (AxisTitle_y == "") { theme(axis.title.y = element_blank()) }
                } +
                scale_x_discrete(labels = label_wrap(TickLabelWidth_x)) +      # Set width of x axis tick mark labels, after which linebreak should occur
                scale_y_continuous(labels = function(value) round(value, Decimals)) +
                ylim(AxisLimits_y[1], AxisLimits_y[2]) +      # Set y axis limits
                {
                  if (!is.null(FillPalette)) { scale_fill_manual(values = FillPalette) }      # Set custom fill color palette}
                  else { scale_color_brewer(name = "Paired") }
                }


    return(Plot)
}
